#!/bin/bash
# Prototype Runnability Verifier
# Tests if the prototype is runnable
# Exit 0 (always - informational)

echo "🔍 Verifying prototype is runnable..." >&2

# Create reports directory
REPORTS_DIR=".claude/reports/rapid-prototyper"
mkdir -p "$REPORTS_DIR"

REPORT_FILE="$REPORTS_DIR/runnable-check.md"

cat > "$REPORT_FILE" <<EOF
# Prototype Runnability Check

Generated: $(date)

## Checks

EOF

RUNNABLE=true

# Check for package.json
if [ -f "package.json" ]; then
    echo "✓ package.json exists" >> "$REPORT_FILE"

    # Check for start script
    if grep -q '"start":' package.json; then
        echo "✓ Start script defined" >> "$REPORT_FILE"

        # Determine package manager
        if [ -f "pnpm-lock.yaml" ]; then
            PKG_MANAGER="pnpm"
        elif [ -f "yarn.lock" ]; then
            PKG_MANAGER="yarn"
        else
            PKG_MANAGER="npm"
        fi

        echo "" >> "$REPORT_FILE"
        echo "**Run command:**" >> "$REPORT_FILE"
        echo "\`\`\`bash" >> "$REPORT_FILE"
        echo "$PKG_MANAGER start" >> "$REPORT_FILE"
        echo "\`\`\`" >> "$REPORT_FILE"
    else
        echo "⚠️  No start script defined" >> "$REPORT_FILE"
        RUNNABLE=false
    fi

    # Check for node_modules
    if [ -d "node_modules" ]; then
        echo "✓ Dependencies installed" >> "$REPORT_FILE"
    else
        echo "❌ Dependencies not installed - run: $PKG_MANAGER install" >> "$REPORT_FILE"
        RUNNABLE=false
    fi
else
    echo "ℹ️  No package.json - not a Node.js project" >> "$REPORT_FILE"
fi

# Check for PHP files (WordPress theme/plugin)
if [ -f "index.php" ] || [ -f "functions.php" ] || [ -f "style.css" ]; then
    echo "" >> "$REPORT_FILE"
    echo "**WordPress Theme/Plugin detected**" >> "$REPORT_FILE"

    if command -v php &> /dev/null; then
        echo "✓ PHP installed" >> "$REPORT_FILE"
    else
        echo "❌ PHP not installed" >> "$REPORT_FILE"
        RUNNABLE=false
    fi

    if command -v wp &> /dev/null; then
        echo "✓ WP-CLI installed" >> "$REPORT_FILE"
    else
        echo "⚠️  WP-CLI not installed (optional)" >> "$REPORT_FILE"
    fi
fi

# Summary
echo "" >> "$REPORT_FILE"
echo "## Summary" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

if [ "$RUNNABLE" = true ]; then
    echo "✅ **Status:** Prototype appears runnable" >> "$REPORT_FILE"
    echo "✅ Prototype appears runnable" >&2
else
    echo "⚠️  **Status:** Some prerequisites missing" >> "$REPORT_FILE"
    echo "⚠️  Some prerequisites missing - check report" >&2
fi

echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "*Generated by rapid-prototyper agent*" >> "$REPORT_FILE"

echo "📄 Runnable check report: $REPORT_FILE" >&2

exit 0
