#!/bin/bash
# Build Status Reporter
# Generates build status report when agent completes
# Exit 0 (always - informational)

# Create reports directory
REPORTS_DIR=".claude/reports/frontend-developer"
mkdir -p "$REPORTS_DIR"

# Create build report
REPORT_FILE="$REPORTS_DIR/build-status.md"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

cat > "$REPORT_FILE" <<EOF
# Frontend Build Status Report

Generated: $(date)

## Build Status

EOF

# Check if package.json exists
if [ ! -f "package.json" ]; then
    echo "ℹ️  No package.json found - not a Node.js project" >> "$REPORT_FILE"
    exit 0
fi

# Determine package manager
if [ -f "pnpm-lock.yaml" ]; then
    PKG_MANAGER="pnpm"
    LOCK_FILE="pnpm-lock.yaml"
elif [ -f "yarn.lock" ]; then
    PKG_MANAGER="yarn"
    LOCK_FILE="yarn.lock"
else
    PKG_MANAGER="npm"
    LOCK_FILE="package-lock.json"
fi

echo "**Package Manager:** $PKG_MANAGER" >> "$REPORT_FILE"
echo "**Lock File:** $LOCK_FILE" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Check if build script exists
if grep -q '"build":' package.json; then
    echo "### Build Script" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"

    BUILD_SCRIPT=$(grep '"build":' package.json | sed 's/.*"build": "\(.*\)".*/\1/')
    echo "\`\`\`" >> "$REPORT_FILE"
    echo "$BUILD_SCRIPT" >> "$REPORT_FILE"
    echo "\`\`\`" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"

    # Try to run build
    echo "### Build Test" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"

    BUILD_OUTPUT=$($PKG_MANAGER run build 2>&1)
    BUILD_EXIT_CODE=$?

    if [ $BUILD_EXIT_CODE -eq 0 ]; then
        echo "✅ **Build Status:** PASSING" >> "$REPORT_FILE"
    else
        echo "❌ **Build Status:** FAILING" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
        echo "**Error Output:**" >> "$REPORT_FILE"
        echo "\`\`\`" >> "$REPORT_FILE"
        echo "$BUILD_OUTPUT" | tail -n 50 >> "$REPORT_FILE"
        echo "\`\`\`" >> "$REPORT_FILE"
    fi
else
    echo "ℹ️  No build script defined in package.json" >> "$REPORT_FILE"
fi

echo "" >> "$REPORT_FILE"

# Check for linting
echo "### Linting Configuration" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

LINTERS=()
[ -f ".eslintrc.js" ] || [ -f ".eslintrc.json" ] || [ -f "eslint.config.js" ] && LINTERS+=("ESLint")
[ -f ".stylelintrc.js" ] || [ -f ".stylelintrc.json" ] && LINTERS+=("Stylelint")
[ -f ".prettierrc" ] || [ -f ".prettierrc.js" ] || [ -f ".prettierrc.json" ] && LINTERS+=("Prettier")

if [ ${#LINTERS[@]} -gt 0 ]; then
    for linter in "${LINTERS[@]}"; do
        echo "- ✓ $linter configured" >> "$REPORT_FILE"
    done
else
    echo "- No linters configured" >> "$REPORT_FILE"
fi

echo "" >> "$REPORT_FILE"

# Check for TypeScript
if [ -f "tsconfig.json" ]; then
    echo "### TypeScript" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo "✓ TypeScript configured" >> "$REPORT_FILE"

    if command -v tsc &> /dev/null || [ -f "node_modules/.bin/tsc" ]; then
        echo "" >> "$REPORT_FILE"
        echo "**Type Check:**" >> "$REPORT_FILE"

        TS_OUTPUT=$(npx tsc --noEmit 2>&1)
        TS_EXIT_CODE=$?

        if [ $TS_EXIT_CODE -eq 0 ]; then
            echo "- ✅ No type errors" >> "$REPORT_FILE"
        else
            echo "- ❌ Type errors found" >> "$REPORT_FILE"
            echo "" >> "$REPORT_FILE"
            echo "\`\`\`" >> "$REPORT_FILE"
            echo "$TS_OUTPUT" | head -n 20 >> "$REPORT_FILE"
            echo "\`\`\`" >> "$REPORT_FILE"
        fi
    fi
fi

echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "*Generated by frontend-developer agent*" >> "$REPORT_FILE"

echo "✅ Build status report generated: $REPORT_FILE" >&2

exit 0
