#!/bin/bash
# Docusaurus Preview Link Generator
# Generates preview link/instructions when agent completes
# Exit 0 (always - informational)

# Check if this is a Docusaurus project
if [ ! -f "docusaurus.config.js" ] && [ ! -f "docusaurus.config.ts" ]; then
    echo "ℹ️  Not a Docusaurus project" >&2
    exit 0
fi

# Create reports directory
REPORTS_DIR=".claude/reports/docusaurus-expert"
mkdir -p "$REPORTS_DIR"

# Create preview instructions
PREVIEW_FILE="$REPORTS_DIR/preview-instructions.md"
cat > "$PREVIEW_FILE" <<EOF
# Docusaurus Preview Instructions

Generated: $(date)

## Local Development Server

To preview the documentation locally:

\`\`\`bash
# Start development server
EOF

# Determine package manager
if [ -f "pnpm-lock.yaml" ]; then
    PKG_MANAGER="pnpm"
elif [ -f "yarn.lock" ]; then
    PKG_MANAGER="yarn"
else
    PKG_MANAGER="npm"
fi

echo "$PKG_MANAGER start" >> "$PREVIEW_FILE"

cat >> "$PREVIEW_FILE" <<EOF
\`\`\`

The site will open at: http://localhost:3000

## Build for Production

To build the static site:

\`\`\`bash
$PKG_MANAGER run build
\`\`\`

## Serve Production Build

To preview the production build locally:

\`\`\`bash
$PKG_MANAGER run serve
\`\`\`

The site will open at: http://localhost:3000

## Deployment

EOF

# Check for deployment configuration
if [ -f "vercel.json" ]; then
    cat >> "$PREVIEW_FILE" <<EOF
### Vercel

This project is configured for Vercel deployment.

\`\`\`bash
# Install Vercel CLI
npm install -g vercel

# Deploy
vercel
\`\`\`

EOF
fi

if [ -f "netlify.toml" ]; then
    cat >> "$PREVIEW_FILE" <<EOF
### Netlify

This project is configured for Netlify deployment.

\`\`\`bash
# Install Netlify CLI
npm install -g netlify-cli

# Deploy
netlify deploy
\`\`\`

EOF
fi

if grep -q "gh-pages" package.json 2>/dev/null; then
    cat >> "$PREVIEW_FILE" <<EOF
### GitHub Pages

This project is configured for GitHub Pages deployment.

\`\`\`bash
# Deploy to GitHub Pages
GIT_USER=<Your GitHub username> $PKG_MANAGER run deploy
\`\`\`

EOF
fi

# Check if build exists
if [ -d "build" ]; then
    BUILD_SIZE=$(du -sh build 2>/dev/null | cut -f1)
    PAGE_COUNT=$(find build -name "*.html" | wc -l)

    cat >> "$PREVIEW_FILE" <<EOF
## Build Information

- Build directory: \`build/\`
- Build size: $BUILD_SIZE
- HTML pages: $PAGE_COUNT

EOF
fi

cat >> "$PREVIEW_FILE" <<EOF
---

*Generated by docusaurus-expert agent*
EOF

echo "✅ Preview instructions generated: $PREVIEW_FILE" >&2

# Try to detect and display the site URL from config
if [ -f "docusaurus.config.js" ]; then
    SITE_URL=$(grep -E "^\s*url:" docusaurus.config.js | grep -oE 'https?://[^"'\'']+' || true)
    if [ -n "$SITE_URL" ]; then
        echo "   Site URL (from config): $SITE_URL" >&2
    fi
fi

exit 0
