#!/bin/bash
# API Test Summary Generator
# Generates comprehensive test summary when agent completes
# Exit 0 (always - informational)

# Create reports directory
REPORTS_DIR=".claude/reports/api-tester"
mkdir -p "$REPORTS_DIR"

# Check if any test results were saved
if [ ! -d "$REPORTS_DIR" ] || [ -z "$(ls -A "$REPORTS_DIR" 2>/dev/null)" ]; then
    echo "ℹ️  No API test results to summarize" >&2
    exit 0
fi

# Count test runs
TEST_RUNS=$(find "$REPORTS_DIR" -maxdepth 1 -type d -name "test_*" | wc -l)

if [ "$TEST_RUNS" -eq 0 ]; then
    echo "ℹ️  No test runs found" >&2
    exit 0
fi

# Create summary report
SUMMARY_FILE="$REPORTS_DIR/summary.md"
cat > "$SUMMARY_FILE" <<EOF
# API Test Summary

Generated: $(date)

## Test Runs

EOF

# List all test runs
RUNS=()
for test_dir in "$REPORTS_DIR"/test_*; do
    if [ -d "$test_dir" ]; then
        RUNS+=("$test_dir")
    fi
done

# Sort runs by timestamp (newest first)
IFS=$'\n' SORTED_RUNS=($(sort -r <<<"${RUNS[*]}"))
unset IFS

# Process each run
TOTAL_PASSED=0
TOTAL_FAILED=0
TOTAL_REQUESTS=0

for test_dir in "${SORTED_RUNS[@]}"; do
    DIR_NAME=$(basename "$test_dir")
    TIMESTAMP=${DIR_NAME#test_}

    # Format timestamp for display
    YEAR=${TIMESTAMP:0:4}
    MONTH=${TIMESTAMP:4:2}
    DAY=${TIMESTAMP:6:2}
    HOUR=${TIMESTAMP:9:2}
    MINUTE=${TIMESTAMP:11:2}
    SECOND=${TIMESTAMP:13:2}

    FORMATTED_DATE="$YEAR-$MONTH-$DAY $HOUR:$MINUTE:$SECOND"

    echo "### Run: $FORMATTED_DATE" >> "$SUMMARY_FILE"
    echo "" >> "$SUMMARY_FILE"

    # Add summary if it exists
    if [ -f "$test_dir/summary.txt" ]; then
        echo "\`\`\`" >> "$SUMMARY_FILE"
        cat "$test_dir/summary.txt" >> "$SUMMARY_FILE"
        echo "\`\`\`" >> "$SUMMARY_FILE"

        # Extract statistics if available
        if grep -q "Total Requests:" "$test_dir/summary.txt"; then
            REQUESTS=$(grep "Total Requests:" "$test_dir/summary.txt" | grep -oE '[0-9]+')
            PASSED=$(grep "Passed:" "$test_dir/summary.txt" | grep -oE '[0-9]+')
            FAILED=$(grep "Failed:" "$test_dir/summary.txt" | grep -oE '[0-9]+')

            TOTAL_REQUESTS=$((TOTAL_REQUESTS + REQUESTS))
            TOTAL_PASSED=$((TOTAL_PASSED + PASSED))
            TOTAL_FAILED=$((TOTAL_FAILED + FAILED))
        fi
    fi

    echo "" >> "$SUMMARY_FILE"
    echo "**Files:** [View results](./$DIR_NAME/)" >> "$SUMMARY_FILE"
    echo "" >> "$SUMMARY_FILE"
    echo "---" >> "$SUMMARY_FILE"
    echo "" >> "$SUMMARY_FILE"
done

# Add overall statistics
echo "## Overall Statistics" >> "$SUMMARY_FILE"
echo "" >> "$SUMMARY_FILE"
echo "- Total test runs: $TEST_RUNS" >> "$SUMMARY_FILE"

if [ $TOTAL_REQUESTS -gt 0 ]; then
    echo "- Total API requests: $TOTAL_REQUESTS" >> "$SUMMARY_FILE"
    echo "- Passed: $TOTAL_PASSED" >> "$SUMMARY_FILE"
    echo "- Failed: $TOTAL_FAILED" >> "$SUMMARY_FILE"

    SUCCESS_RATE=$(echo "scale=2; ($TOTAL_PASSED * 100) / $TOTAL_REQUESTS" | bc 2>/dev/null || echo "0")
    echo "- Success rate: ${SUCCESS_RATE}%" >> "$SUMMARY_FILE"
fi

echo "" >> "$SUMMARY_FILE"

# Latest run status
if [ ${#SORTED_RUNS[@]} -gt 0 ]; then
    LATEST="${SORTED_RUNS[0]}"
    echo "## Latest Test Run" >> "$SUMMARY_FILE"
    echo "" >> "$SUMMARY_FILE"
    echo "**Run:** $(basename "$LATEST")" >> "$SUMMARY_FILE"

    if [ -f "$LATEST/newman-report.json" ]; then
        LATEST_TOTAL=$(jq -r '.run.stats.requests.total // 0' "$LATEST/newman-report.json" 2>/dev/null)
        LATEST_FAILED=$(jq -r '.run.stats.requests.failed // 0' "$LATEST/newman-report.json" 2>/dev/null)

        if [ "$LATEST_FAILED" -eq 0 ]; then
            echo "**Status:** ✅ All tests passed" >> "$SUMMARY_FILE"
        else
            echo "**Status:** ❌ $LATEST_FAILED/$LATEST_TOTAL tests failed" >> "$SUMMARY_FILE"
        fi
    fi
fi

echo "" >> "$SUMMARY_FILE"
echo "---" >> "$SUMMARY_FILE"
echo "*Generated by api-tester agent*" >> "$SUMMARY_FILE"

echo "✅ API test summary generated: $SUMMARY_FILE" >&2
echo "   Total test runs: $TEST_RUNS" >&2

exit 0
