#!/bin/bash
# MCP Setup Documentation Generator
# Generates setup instructions for MCP configuration
# Exit 0 (always - informational)

# Create reports directory
REPORTS_DIR=".claude/reports/mcp-expert"
mkdir -p "$REPORTS_DIR"

# Look for MCP configuration files
MCP_CONFIGS=()
[[ -f "claude_desktop_config.json" ]] && MCP_CONFIGS+=(claude_desktop_config.json)
[[ -f "mcp.json" ]] && MCP_CONFIGS+=(mcp.json)
[[ -f "mcp-config.json" ]] && MCP_CONFIGS+=(mcp-config.json)

if [ ${#MCP_CONFIGS[@]} -eq 0 ]; then
    echo "ℹ️  No MCP configuration files found" >&2
    exit 0
fi

# Generate documentation
DOCS_FILE="$REPORTS_DIR/setup-instructions.md"

cat > "$DOCS_FILE" <<EOF
# MCP Setup Instructions

Generated: $(date)

## Configuration Files

EOF

for config in "${MCP_CONFIGS[@]}"; do
    echo "- \`$config\`" >> "$DOCS_FILE"
done

echo "" >> "$DOCS_FILE"

# Process each configuration
for config in "${MCP_CONFIGS[@]}"; do
    # Strip comments if .jsonc
    if [[ "$config" =~ \.jsonc$ ]]; then
        CONTENT=$(grep -v '^\s*//' "$config")
    else
        CONTENT=$(cat "$config")
    fi

    if ! echo "$CONTENT" | jq '.' > /dev/null 2>&1; then
        continue
    fi

    if echo "$CONTENT" | jq -e '.mcpServers' > /dev/null 2>&1; then
        SERVERS=$(echo "$CONTENT" | jq -r '.mcpServers | keys[]')

        cat >> "$DOCS_FILE" <<EOF
## MCP Servers in \`$config\`

EOF

        for server in $SERVERS; do
            COMMAND=$(echo "$CONTENT" | jq -r ".mcpServers.\"$server\".command")
            ARGS=$(echo "$CONTENT" | jq -r ".mcpServers.\"$server\".args // [] | join(\" \")")

            cat >> "$DOCS_FILE" <<EOF
### $server

**Command:** \`$COMMAND $ARGS\`

EOF

            # Installation instructions
            if echo "$COMMAND" | grep -q "npx"; then
                PACKAGE=$(echo "$ARGS" | awk '{print $1}')
                cat >> "$DOCS_FILE" <<EOF
**Installation:**
\`\`\`bash
npm install -g $PACKAGE
\`\`\`

EOF
            elif echo "$COMMAND" | grep -q "node"; then
                cat >> "$DOCS_FILE" <<EOF
**Installation:**
\`\`\`bash
# Ensure Node.js is installed
node --version
\`\`\`

EOF
            fi

            # Environment variables
            if echo "$CONTENT" | jq -e ".mcpServers.\"$server\".env" > /dev/null 2>&1; then
                cat >> "$DOCS_FILE" <<EOF
**Environment Variables:**

EOF
                ENV_VARS=$(echo "$CONTENT" | jq -r ".mcpServers.\"$server\".env | keys[]")
                for var in $ENV_VARS; do
                    echo "- \`$var\`" >> "$DOCS_FILE"
                done
                echo "" >> "$DOCS_FILE"
            fi

            echo "---" >> "$DOCS_FILE"
            echo "" >> "$DOCS_FILE"
        done
    fi
done

# Add general setup instructions
cat >> "$DOCS_FILE" <<EOF
## General Setup

### For Claude Desktop

1. Copy the MCP configuration to your Claude Desktop config directory:
   - **macOS:** \`~/Library/Application Support/Claude/claude_desktop_config.json\`
   - **Windows:** \`%APPDATA%\Claude\claude_desktop_config.json\`
   - **Linux:** \`~/.config/Claude/claude_desktop_config.json\`

2. Restart Claude Desktop

### For Claude Code

MCP servers are automatically loaded from \`mcp.json\` or \`claude_desktop_config.json\` in your project directory.

## Testing

Test your MCP configuration:

\`\`\`bash
# Validate JSON syntax
jq '.' claude_desktop_config.json

# Test each server command individually
node path/to/server.js --version
\`\`\`

---

*Generated by mcp-expert agent*
EOF

echo "✅ MCP setup documentation generated: $DOCS_FILE" >&2

exit 0
